spring:
  thymeleaf:
    #????
    cache: false
  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: oracle.jdbc.OracleDriver
    #url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEcoding=UTF-8&serverTimezone=Asia/Shanghai
    url: jdbc:oracle:thin:@123.235.9.198:61521:orcl
    username: ncc0617
    password: ncc0617
    hikari:
      #???name
      pool-name: DateHikariCP
      #???????
      minimum-idle: 5
      #????????
      idle-timeout: 180000
      #?????
      maximum-pool-size: 10
      #??????????????
      auto-commit: true
      #???????? 0?????????1800000?30min?
      max-lifetime: 1800000
      #????????30s
      connection-timeout: 30000
      #????????????
      connection-test-query: SELECT 1

#Mybatis-plus??
mybatis-plus:
  #mapper.xml????
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #??mybatis?????????????????
  type-aliases-package: com.example.entity

#Mybatis SQL??????????????mapper.xml?
logging:
  level:
    com.dk.seckill.mapper: debug



pk_group:
  pk_org:
    pk_dept:
      user_id: 765767


